apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-serving-minikube-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-serving-minikube-operator
  template:
    metadata:
      labels:
        name: knative-serving-minikube-operator
        app: foo-admission-server
    spec:
      serviceAccountName: knative-serving-minikube-operator
      containers:
        - name: knative-serving-minikube-operator
          image: k-s-o-m:latest
          command:
          - knative-serving-minikube-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knative-serving-minikube-operator"
